## Practice for test

In [52]:
#Kernel anaconda pyton 3.13.9
import pandas as pd
import numpy as np

#### Question #1 — FinOps-style aggregation

In [26]:
records = [
    {"service": "Compute", "cost": 120.50},
    {"service": "Storage", "cost": 50.00},
    {"service": "Compute", "cost": 80.00},
    {"service": "Networking", "cost": 30.00},
    {"service": "Storage", "cost": 20.00},
]

In [ ]:
# with pandas
def calculate_cost_by_service(records):
    records_df=pd.DataFrame(records)
    result_df=records_df.groupby('service').sum('cost').sort_values('cost', ascending=False)#records_df.head(10)
    result=result_df.to_dict()['cost']
    return result

print(calculate_cost_by_service(records))

{'Compute': 200.5, 'Storage': 70.0, 'Networking': 30.0}

In [ ]:
from collections import defaultdict

In [38]:
# No pandas
from collections import defaultdict
def calculate_cost_by_service(records):
    totals = defaultdict(float)
    for r in records:
        totals[r["service"]] += r["cost"]
    result = dict(sorted(totals.items(), key=lambda kv: kv[1], reverse=True))

    return result

print(calculate_cost_by_service(records))

{'Compute': 200.5, 'Storage': 70.0, 'Networking': 30.0}

In [41]:
# No pandas 2
def calculate_cost_by_service(records):
    result = {}
    for record in records:
        service = record["service"]
        cost = record.get("cost", 0)
        result[service] = result.get(service, 0) + cost
    return result
print(calculate_cost_by_service(records))

{'Compute': 200.5, 'Storage': 70.0, 'Networking': 30.0}

In [ ]:
#result
"""
{
    "Compute": 200.50,
    "Storage": 70.00,
    "Networking": 30.00
}
"""

'\n{\n    "Compute": 200.50,\n    "Storage": 70.00,\n    "Networking": 30.00\n}\n'

#### Question #2 — Cloud Cost Analysis with pandas

In [68]:
""""
join both tables
summarize by sevice and deppartm sum cost
add rule for 
    WHEN cost >= 2000 THEN 'High'
    WHEN cost >= 1000 THEN 'Medium'
    ELSE 'Low'
"""

'"\njoin both tables\nsummarize by sevice and deppartm sum cost\nadd rule for \n    WHEN cost >= 2000 THEN \'High\'\n    WHEN cost >= 1000 THEN \'Medium\'\n    ELSE \'Low\'\n'

In [43]:
costs = [
    {"project_id": "P001", "service": "Compute", "cost": 1200},
    {"project_id": "P001", "service": "Storage", "cost": 300},
    {"project_id": "P002", "service": "Compute", "cost": 800},
    {"project_id": "P002", "service": "Database", "cost": 1500},
    {"project_id": "P003", "service": "Storage", "cost": 200},
    {"project_id": "P003", "service": "Compute", "cost": 2500},
    {"project_id": "P004", "service": "Compute", "cost": 400},
]
projects = [
    {"project_id": "P001", "department": "Data", "environment": "Production"},
    {"project_id": "P002", "department": "Finance", "environment": "Production"},
    {"project_id": "P003", "department": "Data", "environment": "Development"},
    {"project_id": "P004", "department": "Marketing", "environment": "Development"},
]

In [ ]:
costs_df=pd.DataFrame(costs)
projects_df=pd.DataFrame(projects)

In [47]:
merged_df = costs_df.merge(projects_df, on='project_id', how='left')

In [48]:
merged_df.head(10)

  project_id   service  cost department  environment
0       P001   Compute  1200       Data   Production
1       P001   Storage   300       Data   Production
2       P002   Compute   800    Finance   Production
3       P002  Database  1500    Finance   Production
4       P003   Storage   200       Data  Development
5       P003   Compute  2500       Data  Development
6       P004   Compute   400  Marketing  Development

In [ ]:
grouped_df=merged_df.groupby(['department','service']).sum('cost').sort_values('cost', ascending=False).reset_index()

In [59]:
grouped_df.head(10)

  department   service  cost
0       Data   Compute  3700
1    Finance  Database  1500
2    Finance   Compute   800
3       Data   Storage   500
4  Marketing   Compute   400

In [63]:
grouped_df['classification'] = pd.cut(
    grouped_df['cost'],
    bins=[-float('inf'), 1000, 2000, float('inf')],
    labels=['Low', 'Medium', 'High']
)

In [64]:
grouped_df

  department   service  cost classification
0       Data   Compute  3700           High
1    Finance  Database  1500         Medium
2    Finance   Compute   800            Low
3       Data   Storage   500            Low
4  Marketing   Compute   400            Low

In [67]:
def analyze_cloud_costs(costs, projects):
    costs_df=pd.DataFrame(costs)
    projects_df=pd.DataFrame(projects)
    merged_df = costs_df.merge(projects_df, on='project_id', how='left')
    grouped_df=merged_df.groupby(['department','service']).sum('cost').sort_values('cost', ascending=False).reset_index()
    grouped_df['classification'] = pd.cut(
    grouped_df['cost'],
    bins=[-float('inf'), 1000, 2000, float('inf')],
    labels=['Low', 'Medium', 'High']
    )
    return grouped_df.to_dict(orient='records')

print(analyze_cloud_costs(costs, projects))

[{'department': 'Data', 'service': 'Compute', 'cost': 3700, 'classification': 'High'}, {'department': 'Finance', 'service': 'Database', 'cost': 1500, 'classification': 'Medium'}, {'department': 'Finance', 'service': 'Compute', 'cost': 800, 'classification': 'Low'}, {'department': 'Data', 'service': 'Storage', 'cost': 500, 'classification': 'Low'}, {'department': 'Marketing', 'service': 'Compute', 'cost': 400, 'classification': 'Low'}]